### ISSUE TITLE
current version don't work with latest mysql

### ISSUE THREAD

**Issue by Kinmarui** [pacoorozco/ssham#15]
workaround is to downgrade mysql to 5.7 in docker-compose.yml
https://github.com/laradock/laradock/issues/1390

**Comment by pacoorozco** [comment]
This code needs to be upgrsded to Laravel 5.5+, there are strong reasons to do it, and one is this MySQL support. Let me spent some time on it.

**Comment by pacoorozco** [comment]
Hi @Kinmarui 

I've updated docker-compose to use MySQL 5.7 instead of latest one. You can test it using `dev` branch.

In some days I'll merge to `master`

**Comment by Kinmarui** [comment]
I applied fix manually and can confirm that application worked. Sadly I don't have now much time to do testing, hopefully I'll get back latter next week.
Side note: I'm running docker on windows and had problem with running ./setup.sh since paths were resolved incorrectly, solution was to run docker exec -it bash and manually run commands from setup.sh
