### ISSUE TITLE
docker-compose build return error

### ISSUE THREAD

**Issue by zieru** [pacoorozco/ssham#18]
`ERROR: Service 'web' failed to build: The command '/bin/sh -c apk update     && apk upgrade     && apk add --no-cache bash     && adduser -D -H -u 1000 -s /bin/bash www-data' returned a non-zero code: 1`

**Comment by pacoorozco** [comment]
Hi @zieru 

Please give me more details because it's working for me. 

* Which OS are you using?
* Can you paste the command you executed?
