### ISSUE TITLE
Serving on local network

### ISSUE THREAD

**Issue by loviuz** [pacoorozco/ssham#19]
I am trying to run ssham on local network, but i cannot reach the istance when i run 
`php artisan serve --port=4000`

It says:
`Laravel development server started on http://localhost:4000/`

but the pages are not reachable through http://server_ip:4000. Do i have to change something?

**Comment by pacoorozco** [comment]
Hi @loviuz 

If you use `php artisan serve` you ar attaching a web server only to **localhost**. If you want to use a different host to serve the code you should use `--host[=HOST]`. Take a look at [Laravel documentation](https://laravel.com/docs/5.1/).
