### ISSUE TITLE
trustedproxy.php

### ISSUE THREAD

**Issue by jborrull** [pacoorozco/ssham#50]
Hello,

We've configured the trustedproxy.php with this:

'proxies' => '*',
'headers' => env('TRUSTED_HEADERS', Illuminate\Http\Request::HEADER_X_FORWARDED_ALL),

But when we put the https url, it doesn't work.

Have you got any idea?

Thanks,
Regards,
Joan

**Comment by pacoorozco** [comment]
@jborrull , Can you share the `.env` configuration regarding these two variable `TRUSTED_PROXIES` and `TRUSTED_HEADERS`?

**Comment by jborrull** [comment]
Hello Paco,

Sorry, there are empty,

What should we put here?

Thanks,
Regards,
Joan

**Comment by pacoorozco** [comment]
You should configure there which proxies you trust on and which are the headers you wan to use. 

In your case, it seems you want to trust in all proxies, so `TRUSTED_PROXIES='*'`. Then, depending the proxy you are putting in front of it, you should configure the header to be used... I would suggest to let `TRUSTED_HEADERS` unset to use the default configuration (unless your are using AWS).

If it's not working, *can you describe your setup and the error that you are seeing?*

**Comment by jborrull** [comment]
Hi Paco,

I've configured the TRUSTED_PROXIES=* and TRUSTED_HEADERS (i've tryed empty and with the other options) but it doesn't work. I didn't obtain any error, i see this screen when i try to connect throught https:

![image](https://user-images.githubusercontent.com/72247305/95072785-0cc26300-070c-11eb-943f-6bc3994ff2a5.png)

What do you need to check our configuration?

Thanks,
Regards,
Joan

**Comment by pacoorozco** [comment]
I'm referring to your setup: 

- which load balancer are you using?
- where are you running the app?
- have you reviewed the developer console (F12 on Chrome)?
- Is there any error there? What are the link to css files?
- What is the content of the `APP_URL` variable?

Paco

**Comment by jborrull** [comment]
Hi Paco,

We've done these changes in some files and it's working well

.env:

ENFORCE_SSL=true

app/Providers/AppServiceProvider.php:

 public function boot()
    **_**{
    if(env('ENFORCE_SSL', false)) {
    \Illuminate\Support\Facades\URL::forceScheme('https');
    }**_**
    Response::macro('attachment', function (string $content, string $filename = 'private.key') {
            $headers = [
                'Content-Type' => 'application/pkcs8',
                'Content-Disposition' => 'attachment; filename="' . $filename . '"',
            ];
            return Response::make($content, ResponseCode::HTTP_OK, $headers);
        });
    }
}

** And we've configured trustedproxy.php with our IP's (in the .env file).

Thanks for your support,

Regards,
Joan

**Comment by pacoorozco** [comment]
Uhhm... I'm not sure this change should be needed @jborrull 

Based on your change you have enforced SSL to be used in all URL. I guess that you're terminating SSL in your "proxy", right?

Can you send me a copy of your `.env` file (remove passwords)?

**Comment by jborrull** [comment]
Hi Paco,

Yes, this is our .env file:

APP_NAME=SSHAM
APP_ENV=local
APP_KEY=base64:mjSBP6eyVZMgfu4NQESGIIC55zSLIDHwSPMIJmVnER8=
APP_DEBUG=true
APP_URL=https://ssham.xxx.xxx.es
ENFORCE_SSL=true

# Database configuration.
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=xxx

# Trusted proxies configuration
# @see 'config/trustedproxy.php' to know how to configure these trusted proxies.
TRUSTED_PROXIES=XX.X.X.XXX,XX.X.X.XXX
TRUSTED_HEADERS=HEADER_X_FORWARDED_ALL

# -----[ DO NOT TOUCH BELOW THIS POINT ]-----
#
BROADCAST_DRIVER=log
QUEUE_CONNECTION=sync

LOG_CHANNEL=stack

MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

Regards,
Joan

**Comment by pacoorozco** [comment]
Hi @jborrull 

Now I can see where the problem is. `APP_ENV=local` should be `APP_ENV=production`. Otherwise some internals are not enabled (such `ENFORCE_SSL`) by default.

I suggest to configure `APP_DEBUG=false`, to not show internal messages on errors.

An once you have publish the `APP_KEY`, please modify it using `php artisan key:generate`.

**Comment by pacoorozco** [comment]
I've updated the README to add this information.

**Comment by jborrull** [comment]
Hi Paco,

Ok, perfect, i've changed the APP_KEY with php artisan key:generate

Tomorrow i will check the APP_ENV=production in our aplication and i'll inform you about it,

Thanks,
Regards,
Joan
