### ISSUE TITLE
Manage user authorized_keys under /etc/ssh/authorized_keys/$user

### ISSUE THREAD

**Issue by deepwather** [pacoorozco/ssham#51]
Good afternoon,
We would like to use your ssham in our company for user-ssh key management.

However, our public keys of the users are organized on all servers as follows:

```
u229044@oseadmin01az1 ~$ ls -la /etc/ssh/authorized_keys/
total 88
drwxr-xr-x. 2 root    root 4096 Aug  3 12:39 .
drwxr-xr-x. 3 root    root  248 Jan  6  2020 ..
-r--------. 1 u507889 root  381 Feb  1  2019 u507889
-r--------. 1 u509154 root  398 May  3  2019 u509154
-r--------. 1 u516765 root  740 Apr  1  2019 u516765
-r--------. 1 u518913 root  398 May 10  2019 u518913
-r--------. 1 u522294 root  101 Jan  9  2020 u522294
-r--------. 1 u528010 root  733 May 13 12:06 u528010
-r--------. 1 u529875 root  398 Aug  3 12:38 u529875
-r--------. 1 u529941 root  398 Aug  3 12:39 u529941
...
```

What do we need to change in the code to configure this? Or could you add a suitable option here that this is possible?

Friendly greetings
michu

**Comment by pacoorozco** [comment]
Hi @deepwather 

I can't fully understand your current setup. You're creating these SSH keys in `/etc/ssh/authorized_keys` folder. **How are your users able to login to the server?** **How are you using these keys?**

**Comment by deepwather** [comment]
Hi @pacoorozco 

no problem i will gladly explain the setup to you.

In a larger company environment it is mandatory that every employee has his own linux home to store data or for security reasons.

We have therefore created a separate user with so-called u-numbers for each user:

```
root@oseadmin01az1 ~# ls -la /home/
total 64
drwxr-xr-x. 19 root       root        264 Aug  3 12:33 .
dr-xr-xr-x. 19 root       root        256 Feb 12  2019 ..
drwx------. 11 u210691    u210691    4096 Apr 14 16:35 u210691
drwx------. 24 u212309    u212309    4096 Sep 18 12:39 u212309
drwx------. 18 u216403    u216403    4096 Sep 16 10:20 u216403
drwx------. 32 u219911    u219911    4096 Aug 19 06:20 u219911
drwxr-xr-x. 22 u225900    u225900    4096 Oct  5 11:51 u225900
drwx------. 15 u226791    u226791    4096 Apr 21 08:40 u226791
drwx------. 36 u226980    u226980    4096 Oct  6 18:23 u226980
drwx------. 35 u229044    u229044    4096 Aug 27 12:22 u229044
drwx------. 26 u229412    u229412    4096 Oct  6 11:16 u229412
drwx------. 13 ue63553    ue63553    4096 Jun 18 13:39 ue63553
...
```

The authorized_keys for the users are all located at a central point:

```
root@oseadmin01az1 ~# ls -la /etc/ssh/authorized_keys/
total 88
drwxr-xr-x. 2 root    root 4096 Aug  3 12:39 .
drwxr-xr-x. 3 root    root  248 Oct  7 08:50 ..
-r--------. 1 1043270 root  742 Feb  1  2019 u208371
-r--------. 1 u210691 root  412 Feb  1  2019 u210691
-r--------. 1 u212309 root   95 Feb  1  2019 u212309
-r--------. 1 u216403 root  381 Feb  1  2019 u216403
-r--------. 1 u219911 root  740 Feb  1  2019 u219911
-r--------. 1 u225900 root  721 Feb  1  2019 u225900
-r--------. 1 u226791 root  746 Feb  1  2019 u226791
-r--------. 1 u226980 root   98 Feb  1  2019 u226980
-r--------. 1 u229044 root  737 Jun  5  2019 u229044
-r--------. 1 u229412 root  271 Jul  2  2019 u229412
-r--------. 1 ue63553 root  725 Jan 28  2020 ue63553
```

To ensure that each user has the correct public key to login to the server, we have adapted the sshd_config as follows on all servers via ansible:

```
root@oseadmin01az1 ~# cat /etc/ssh/sshd_config
# Ansible managed

Port 22
ListenAddress 10.107.34.16
Protocol 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
LoginGraceTime 2m

PermitRootLogin no
StrictModes yes
AuthorizedKeysFile /etc/ssh/authorized_keys/%u
HostbasedAuthentication no
IgnoreRhosts yes
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no

ChallengeResponseAuthentication no
UsePAM yes

X11Forwarding yes
UsePrivilegeSeparation yes

Subsystem       sftp    /usr/libexec/openssh/sftp-server
ClientAliveInterval 60
ClientAliveCountMax 5
AllowTcpForwarding yes

LogLevel INFO
MaxAuthTries 4
PermitUserEnvironment no
Ciphers aes128-ctr,aes192-ctr,aes256-ctr
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
MACs hmac-sha2-256,hmac-sha2-512
AllowAgentForwarding yes
```

**Comment by pacoorozco** [comment]
Thanks @deepwather. I guess you are using this setup for all your servers where your users should access. I don't see how SSHAM could help you in this setup, given that you have everything in place. The main pain point that SSHAM is trying to fix is **guarantee access to servers without creating every user in every server**. 

Imagine a fleet of hundred of servers (we had ~700) and a bunch of developers, sys admins , operators (~ 150)... It would be very time demanding to create these 150 users in all the 700 servers, ensuring they only have access to the permissions they need.

For that, we create three accounts in each server (via puppet, ansible...) 'dev', 'oper', 'admin'. Then with SSHAM we allow a person to login with its one SSH key to one, two or all of these accounts in a group of servers. 

We are looking more or less the same, but in your case you **need** a user on the server to have a HOME.
