### ISSUE TITLE
Refine the rules and add a further item "Superuser rights" to the "Allow" "Deny" actions.

### ISSUE THREAD

**Issue by deepwather** [pacoorozco/ssham#52]
To implement a protection policy in a company, all users must have either rights or no rights on the servers. This can also be set up already. But if you want users to have rights as superusers, you cannot set this here today.

Our suggestion: refine the rules and add a further item "Superuser rights" to the "Allow" "Deny" actions.

for users who are then in this group, an additional file is created as follows:

`echo "u229044 ALL=NOPASSWD: ALL" > /etc/sudoers.d/u229044`

Friendly greetings
michu

**Comment by pacoorozco** [comment]
@deepwather I'm afraid that this is out of scope of this project. I mean, the project uses the already created users on the servers, and populate `authorized-keys` files to allow several people (defined by its SSH key) to access to this `user@host`. 

You can have a `admin` user in your servers, with the corresponding `sudoers` configuration. Then you allow/disallow your users to connect to this `admin@host` based on the SSH key.  In the same way, you can have a `regular` user who has not `sudoers` configuration. 

Users with `key1` and `key2` can be allows to login to `admin@host` but user with `key3` is not.

As you can see, you can have the same behaviour without touching your `sudoers` configuration. **What do you think**?

**Comment by deepwather** [comment]
hello @pacoorozco 

This is a good proposal for app server, which is maintained by a few people. 
However, we have about 1000 employees and 300 servers today. With such a large environment, it can happen that up to 60 people work on one server at the same time. 

Among these 60 people, maybe half of them have the right to use docker, others are allowed to access certain NFS shares via group policies and others even have superuser rights. Therefore your solution is not possible in this environment.

My idea last night was to add a `hook` to your `shell script`, which will be started by `artisan` and if "**superuser**" is set to "**allow**" or "**deny**", the script will create a `sudoers` file on the server for this user. 
You could also add a hook, which will be checked by the script when distributing the keys, if this user already exists. If not, it will create the user with `adduser` command.

The keys would then be stored **with the name of the use**r under `/etc/ssh/authorized_keys/%u`

best regards deepwather

**Comment by pacoorozco** [comment]
I think it's a good idea, but if we create things in the "deployer script" we should take care about error handling a so on, what is a bit out of scope. The other point I can foresee is that currently SSHAM doesn't need `root` or `admin` access.. it uses the same user you will share with your employees...
