### ISSUE TITLE
Open questions regarding the usability of ssham

### ISSUE THREAD

**Issue by deepwather** [pacoorozco/ssham#53]
How is a user key distribution started manually?

Is there an internal cronjob for a distribution or is the distribution started when the user changes?

How can we check if a distribution is triggered at all?

What about UID and GID settings?

The best way would be to create a new user via ssham and distribute it to the systems with the key. Is this already the case? 

We do not see any distributed users or keys on our test system.

Friendly greetings
michu

**Comment by pacoorozco** [comment]
Hi @deepwather I'm going to try to cover your questions, **it's already known that we need to complete a documentation site** (sorry about that)...

**How is a user key distribution started manually?**

You can run `php artisan ssham:send` command. If will sync all changes that are pending.

It's worth to explain how it works:

1. It collects all the keys that should have access to a server. 
2. It copies them to the server in the `~/.ssh/authorized_keys-ssham` file. This could be configured by app settings.
3. It also copies [this script](https://github.com/pacoorozco/ssham/blob/master/storage/private/ssham-remote-updater.sh) into `~/.ssh/ssham-remote-updater.sh`. 
4. It calls the previous script on the server to create `~/.ssh/authorized_keys`. It will allow access to the user@host using on of the included SSH keys.

> Transfers are using SFTP and the **bastion host SSH private key** configured at app settings. The corresponding SSH public key needs to be distributed in advance to the servers (puppet, chef...)

**Is there an internal cronjob for a distribution or is the distribution started when the user changes?**

Not yet, there is an issue on the backlog... Right now you can call `php artisan ssham:send` from a cron if you want.

> We need to improve how we are handling errors.

**How can we check if a distribution is triggered at all?**

Yes, everything is logged. Take a look to SSHAM `storage/logs` folder.

**What about UID and GID settings?**

SSHAM will use the configured user to connect to the server. All files will be created using its UID/GID.

**The best way would be to create a new user via ssham and distribute it to the systems with the key. Is this already the case?**

This app is not intended to be used to create users on the servers. The idea is that several people can use its own SSH key to connect to the same server's user without any password sharing.

**Comment by deepwather** [comment]
Hi @pacoorozco 
Ok thank you many times for your exact explanation. I myself am a linux engineer from switzerland but i had little to nothing to do with artisan.

but the explanations have helped me a lot. thanks
