### ISSUE TITLE
Add a web installer to make easier the on-boarding

### ISSUE THREAD

**Issue by pacoorozco** [pacoorozco/ssham#80]
**Is your feature request related to a problem? Please describe.**
The installation forces you to seed the database with useless data.
The default username and password is always the same.

**Describe the solution you'd like**
A web installer that set it up everything in place and allows you to create the first username.

**Describe alternatives you've considered**
An artisan command.

**Comment by scramatte** [comment]
Password must support special characters tool not only digits and letters.

It would be interesting to have basic seed it with only strictly necesary data to get up and running. And another seeding process with extra data mainly for debug and development purpose.

**Comment by pacoorozco** [comment]
The installation process [has been documented](https://ssham.pacoorozco.info/installation/manual/) and it's only few steps. I don't see how a web installer could simplify the installation.
