### ISSUE TITLE
Document how-to add servers to ssham

### ISSUE THREAD

**Issue by pacoorozco** [pacoorozco/ssham#88]
**Is your feature request related to a problem? Please describe.**
Include the documentation to add a new server to `ssham`.

1. Server should contain the **SSHAM public key** on the **authorized file**, before adding it to this app.
2. Differences between strict and mixed mode.
3. How to reconnect an existing server.

**Comment by Shyru** [comment]
We are very interested in using ssham at our company. As such a Guide would be very helpful. Is there anything where we could help/assist with?

**Comment by pacoorozco** [comment]
Sure! I'm going to write a comment to this issue explaining how to use this app. I hope this could be the starting point to write a proper documentation. If you're interested in contributing to the project,you can be the one creating the documentation page xD

**Comment by pacoorozco** [comment]
1. Install the application following [this documentation ](https://github.com/pacoorozco/ssham#how-to-install-ssh-access-manager)
2. Store the public key that has been created during installation (or create a new public/private key pair). This is the **bastion key**.
3. You should add the **bastion public key** to all the ` ~/.ssh/authorized_keys` file in every user/server that you want to manage using SSHAM. The best way to do it is using Puppet, Ansible... you can configure SSH server to allow this key to login to every user in the system (less secure way of doing).
4. Once the previous step is done, the bastion host can ssh to any server with the right user.
5. Go to SSHAM application and add the servers to it.
6. Go to SSHAM application and create new keys (these are the keys that your users will use to login in the servers).
7. Go to SSHAM application and group servers and keys, to define the access policy that you want to force.
8. Go to SSHAM application (or use `php artisan ssham:send` in the Bastion host) to send the new keys to all your servers. SSHAM will use the **Bastion private key** to login and modify ` ~/.ssh/authorized_keys` automatically.
